### ISSUE TITLE
As a User I want to have some mechanism to exclude unwanted operation classes in YML config 

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh-poc#9]
### Example

``` yaml

---
packages-to-scan:
  - com.test.{except DummyOperation, FakeOperation, IgnoredAction}
  - org.test.operation.*
classes:
  - com.jaspersoft.jasperserver.jrsh.core.operation.impl.DummyOperation
```

In the code above I specify a package to scan (`com.test.*`) and excludу classes from that package: `DummyOperation`, `FakeOperation`, and `IgnoredAction`. It is some kind of filter, a convenient filter.
